### PR TITLE
Allow Symfony3

### PR DESCRIPTION
**Pull request by garak**

### CODE REVIEW

**Comment by garak** [comment]
I also squashed commits. Can your merge please?

**Comment by robations** [comment]
Works for me.

**Comment by garak** [comment]
Any news?

**Comment by yohang** [comment]
Seems fine, thanks.

**Comment by garak** [comment]
What about a new tag?

**Comment by yohang** [comment]
Master branch will be tagged 2.0, as there is some BC breaks, and 2.0 is not ready ATM.

**Comment by garak** [comment]
What about 1.1.2 tag?

**Comment by yohang** [comment]
Yep. I'll cherry-pick this commit into 1.1.

**Comment by garak** [comment]
Great! Thank you

**Comment by yohang** [comment]
Hum. Badly, that's not possible. 1.1 version is tied to symfony >= 2.3, wich is incompatible with the new OptionsResolver. 

The only way to made 1.1 compatible with Symfony 3 is to bump the symfony requirement to >= 2.7, and... That's a BC break.

I'll release 2.0, but documentation won't be in sync.

**Pull request merged**
