### PR TITLE
Create .gitattributes

### PR DESCRIPTION
**Pull request by garak**

### CODE REVIEW

**Comment by yohang** [comment]
Closing as the PR is 2 years old and do not have any description.

**Comment by garak** [comment]
Well, I was thinking it was self-explicative: `.gitattributes` file is meant to exclude some dev-only files from final packages. It'a pretty common practice.
Do you mind to re-open?

**Comment by yohang** [comment]
Okay.

However, they're a few files we have to keep in prod packages. Especially `composer.json`, `CHANGELOG` and `README`.

Can you make the modification or do I do it myself ?

**Comment by garak** [comment]
Of course

**Comment by yohang** [comment]
Thank you !

**Pull request merged**
